### ISSUE TITLE
Правильное написание название

### ISSUE THREAD

**Issue by X1Z53** [alt-gnome/nautilus-backspace#8]
Каково правильное название?
- Nautilus backspace
- Nautilus Backspace ([оригинальный репозиторий](https://github.com/riclc/nautilus_backspace))
- Nautilus Backspace Back ([ALT Gnome Wiki](https://alt-gnome.wiki/nautilus-backspace-back.html))

**Comment by Rirusha** [comment]
Nautilus Backspace

**Comment by Rirusha** [comment]
> * Nautilus Backspace Back

Как такое вообще родилось?

**Comment by X1Z53** [comment]
> > Nautilus Backspace Back
> 
> Как такое вообще родилось?

Как-то...
